$setupChefServer = <<SHELL
  wget https://packages.chef.io/stable/ubuntu/14.04/chef-server-core_12.5.0-1_amd64.deb -q
  dpkg -i chef-server-core_*.deb
  chef-server-ctl reconfigure
  chef-server-ctl user-create admin admin admin admin@example.com examplepass -f admin.pem
  chef-server-ctl org-create dips "DIPS ASA" --association_user admin -f dips-validator.pem
  
  chef-manage-ctl reconfigure
  chef-server-ctl install chef-manage
  chef-server-ctl reconfigure
  chef-manage-ctl reconfigure
  
  chef-server-ctl install opscode-reporting
  chef-server-ctl reconfigure
  opscode-reporting-ctl reconfigure
SHELL

Vagrant.configure("2") do |config|
  config.vm.define "master", primary: true do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.network "private_network", ip: "192.168.1.2"
    master.vm.host_name = 'chefserver.vagrant.local'
    master.vm.provision "shell", inline: $setupChefServer
    
    master.vm.network "forwarded_port", guest: 80, host: 4000
    
    master.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
    end
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/trusty64"
    node1.vm.network "private_network", ip: "192.168.1.3"
    node1.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end
  
  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/trusty64"
    node2.vm.network "private_network", ip: "192.168.1.4"
    node2.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end
end